#	 __  .___  ___. .______     ______   .______   .__________.    ___      .__   __. .__________.
#	|  | |   \/   | |   _  \   /  __  \  |   _  \  |          |   /   \     |  \ |  | |          |
#	|  | |  \  /  | |  |_)  | |  |  |  | |  |_)  | `---|  |---`  /  ^  \    |   \|  | `---|  |---`
#	|  | |  |\/|  | |   ___/  |  |  |  | |      /      |  |     /  /_\  \   |  . `  |     |  |
#	|  | |  |  |  | |  |      |  `--'  | |  |\  \_     |  |    /  _____  \  |  |\   |     |  |
#	|__| |__|  |__| | _|       \______/  | _| `.__|    |__|   /__/     \__\ |__| \__|     |__|
#
#
# This is the main config file for strava-ical.
# Any changes to this config should be reflected in the struct `structs.Config`

stravaClientId = 12345
stravaClientSecret = "abcdef12345"

jwtKey = "this is a super secret key. please replace me."
jwtCookieName = "strava-ical-jwt"

dbPath = "./db.sqlite"

# This is the config for the server
[server]
	address	= "strava.cyclingapps.tech"
	port 	= 3000
	timeout	= 0

# This is the default config for the VCalendar
[calendar]
	PRODID          = "-//Cycling Apps//Strava//EN"
	URL             = "http:/cyclingapps.tech/"
	NAME            = "Strava Activities"
	X_WR_CALNAME    = "Strava Activities"
	TIMEZONE_ID     = "Europe/London"
	X_WR_TIMEZONE   = "Europe/London"
	REFRESH_INTERVAL    = "PT12H"
	X_PUBLISHED_TTL     = "PT12H"
	METHOD      = "PUBLIC"
	VERSION     = "2.0"
	CALSCALE    = "GREGORIAN"

[slugs]
    login           = "/login"
    oauth           = "/auth"
    oauthcallback   = "/exchange_token"
    calendars       = "/calendars"