#	 __  .___  ___. .______     ______   .______   .__________.    ___      .__   __. .__________.
#	|  | |   \/   | |   _  \   /  __  \  |   _  \  |          |   /   \     |  \ |  | |          |
#	|  | |  \  /  | |  |_)  | |  |  |  | |  |_)  | `---|  |---`  /  ^  \    |   \|  | `---|  |---`
#	|  | |  |\/|  | |   ___/  |  |  |  | |      /      |  |     /  /_\  \   |  . `  |     |  |
#	|  | |  |  |  | |  |      |  `--'  | |  |\  \_     |  |    /  _____  \  |  |\   |     |  |
#	|__| |__|  |__| | _|       \______/  | _| `.__|    |__|   /__/     \__\ |__| \__|     |__|
#
#
# This is the main config file for strava-ical.
# Any changes to this config should be reflected in the struct `structs.Config`

stravaApiKey = "abdef12345678"
stravaAthleteId = 12345678

shortName	= "Strava"
longName	= "Strava"
calendarDescription = """*** Warning - This feature is currently proof of concept. Information is not guaranteed to be correct. ***"""

calendarEntryName = """{{.Name}}"""
calendarEntryDescription ="""Distance: {{.Distance}}km"""

# This is the config for the server
[server]
	address	= "localhost"
	port 	= 3000
	timeout	= 0

# This is the default config for the VCalendar
[calendar]
	PRODID			= "-//ChrisTheBaron//Strava//EN"
	URL				= "http:/christhebaron.co.uk/"
	NAME			= "Strava"
	X_WR_CALNAME	= "Strava"
	TIMEZONE_ID		= "Europe/London"
	X_WR_TIMEZONE	= "Europe/London"
	REFRESH_INTERVAL	= "PT12H"
	X_PUBLISHED_TTL		= "PT12H"
	METHOD		= "PUBLIC"
	VERSION		= "2.0"
	CALSCALE	= "GREGORIAN"
